<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Formulaire
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="style.css" />
    </head>
    <body id="form">
        <main>
            <form method="get" action="index.php">
                <section>
                    <h3>
                        Informations
                    </h3>
                    <?php require './informations.phtml'; ?>
                    <h4>
                        Langues
                    </h4>
                    <?php require './langue.phtml'; ?>
                </section>
                <section>
                    <h3>
                        Compétences
                    </h3>
                    <h4>
                        Langages de Programmation
                    </h4>
                    <?php require './Languprog.phtml'; ?> 
                    <h4>
                        Frameworks & Librairies
                    </h4>
                    <?php require './framew.phtml'; ?>
                    <h4>
                        Logiciels
                    </h4>
                    <?php require './logiciel.phtml'; ?>
                    <h4>
                        Couleur du CV
                    </h4>
                    <fieldset id="select">
                        <label for="color">Couleur</label>
                        <select name="color" id="color">
                            <option name="bleu" value="blue">Bleu</option>
                            <option name="rouge" value="red">Rouge</option>
                        </select>
                    </fieldset>
                </section>
                <input type="submit" value="Envoyer" />
            </form>
        </main>
    </body>
</html>